[project]
name = "sattracer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shivam Kumar", email = "shivam.kumar.101075@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.5",
    "folium>=0.20.0",
    "geopandas>=1.1.4",
    "geopy>=2.5.0",
    "nominatim>=0.1",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "streamlit>=1.63.0",
    "streamlit-folium>=0.27.4",
    "streamlit-searchbox>=0.1.24",
    "tqdm>=4.70.0",
]

[project.scripts]
sattracer = "sattracer:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
